### ISSUE TITLE
请求Fork以搭建自己的博客

### ISSUE THREAD

**Issue by LIUBINfighter** [chanbengz/chanbengz.github.io#1]
学长好！

我是妮可23级信管系本科生，最近通过朋友分享的加密学笔记在GitHub上发现了您的博客，觉得排版和视觉效果都很不错，对使用它来搭建个人博客非常感兴趣。我请求Fork您的仓库搭建自己的博客，并希望能得到一些指导。

请问您能提供一些基本的步骤或资源链接，帮助我了解如何开始吗？我正在尝试阅读您的仓库。

我对如何添加新的文章感兴趣（没头绪），如果您有相关的示例或文档，那将非常有帮助。

非常感谢您的时间和帮助。并期待您的回复。

祝暑好！

**Comment by chanbengz** [comment]
> ~~加密学~~ ❎ 密码学 ✅

感谢你的欣赏。本博客非常粗糙，实在拿不出手（

其实`Fork`的本意是你可以contribute一些内容或者修改意见到我的博客，repo作者检查之后合并到主分支，而不是当作「模版」或「收藏(Star)」。如果你想学习使用Github为开源项目做贡献，可以尝试Fork之后，提交(commit)一些修改(可以帮忙找找typo或者格式错误)，然后在repo界面创建Pull Request。欢迎你在这个repo练手。

本博客是用现成框架搭建的，只有文章源码和一些配置文件，再通过Github Actions构建静态网页并部署到Github Pages提供的托管服务器。因此不推荐以本仓库为模版或者例子来尝试学习。模版其实网上也有很多教程，我知道几个比较流行的框架有Hexo(曾经用过), Hugo(现在用的), WordPress(不推荐), VuePress, GitBook, Mkdoc等等，这几个的特点对比可以自行了解下。每个框架还有自己的主题和插件，挺复杂的，但我建议都去看看，然后再做决定。

稍后我会整理一个本博客的搭建教程，或者你可以直接联系我（wechat: real_chanben)。其实其他人在这个模版上还自定义了很多功能（比如美化，评论功能，流量统计等），因为我比较懒就没搞那么多。

祝折腾顺利！

**Comment by chanbengz** [comment]
看你貌似对区块链很感兴趣，但我的笔记还没有写到零知识证明那一部分，有空就补（

打个小广告，妮可的CTF战队也有研究Web3的，主要是关于智能合约/以太坊安全

欢迎来交流，群号：787427165

**Comment by LIUBINfighter** [comment]
Got it, fork完了自己弄这个习惯是从academic page那里学来的（，但是自己实在没有什么拿得出手的成就就决定先写博客积累了

最近正在阅读零知识证明的一篇综述，头大得很，期待学长的笔记。

Hugo在Go了在Go了（bushi），还是决定搭配文档自己弄个出来看看效果先。有问题俺再来请教
